service: git-herald

provider:
  name: aws
  runtime: nodejs4.3
  profile: ${opt:profile}
  stage: ${opt:stage}
  region: us-east-1

functions:
  gitHerald:
    handler: handler.gitHerald
    events:
      - http: POST git-herald
